// Complete Periodic Table data - all 118 elements with grid positions
// row/col follow standard periodic table layout (1-indexed)
export const ELEMENTS = [
  // Period 1
  { z: 1, symbol: 'H', name: 'Hiđro', nameEn: 'Hydrogen', mass: 1.008, category: 'nonmetal', row: 1, col: 1 },
  { z: 2, symbol: 'He', name: 'Heli', nameEn: 'Helium', mass: 4.003, category: 'noble-gas', row: 1, col: 18 },
  // Period 2
  { z: 3, symbol: 'Li', name: 'Liti', nameEn: 'Lithium', mass: 6.941, category: 'alkali-metal', row: 2, col: 1 },
  { z: 4, symbol: 'Be', name: 'Beri', nameEn: 'Beryllium', mass: 9.012, category: 'alkaline-earth', row: 2, col: 2 },
  { z: 5, symbol: 'B', name: 'Bo', nameEn: 'Boron', mass: 10.81, category: 'metalloid', row: 2, col: 13 },
  { z: 6, symbol: 'C', name: 'Cacbon', nameEn: 'Carbon', mass: 12.01, category: 'nonmetal', row: 2, col: 14 },
  { z: 7, symbol: 'N', name: 'Nitơ', nameEn: 'Nitrogen', mass: 14.01, category: 'nonmetal', row: 2, col: 15 },
  { z: 8, symbol: 'O', name: 'Oxi', nameEn: 'Oxygen', mass: 16.00, category: 'nonmetal', row: 2, col: 16 },
  { z: 9, symbol: 'F', name: 'Flo', nameEn: 'Fluorine', mass: 19.00, category: 'halogen', row: 2, col: 17 },
  { z: 10, symbol: 'Ne', name: 'Neon', nameEn: 'Neon', mass: 20.18, category: 'noble-gas', row: 2, col: 18 },
  // Period 3
  { z: 11, symbol: 'Na', name: 'Natri', nameEn: 'Sodium', mass: 22.99, category: 'alkali-metal', row: 3, col: 1 },
  { z: 12, symbol: 'Mg', name: 'Magie', nameEn: 'Magnesium', mass: 24.31, category: 'alkaline-earth', row: 3, col: 2 },
  { z: 13, symbol: 'Al', name: 'Nhôm', nameEn: 'Aluminium', mass: 26.98, category: 'post-transition', row: 3, col: 13 },
  { z: 14, symbol: 'Si', name: 'Silic', nameEn: 'Silicon', mass: 28.09, category: 'metalloid', row: 3, col: 14 },
  { z: 15, symbol: 'P', name: 'Photpho', nameEn: 'Phosphorus', mass: 30.97, category: 'nonmetal', row: 3, col: 15 },
  { z: 16, symbol: 'S', name: 'Lưu huỳnh', nameEn: 'Sulfur', mass: 32.07, category: 'nonmetal', row: 3, col: 16 },
  { z: 17, symbol: 'Cl', name: 'Clo', nameEn: 'Chlorine', mass: 35.45, category: 'halogen', row: 3, col: 17 },
  { z: 18, symbol: 'Ar', name: 'Argon', nameEn: 'Argon', mass: 39.95, category: 'noble-gas', row: 3, col: 18 },
  // Period 4
  { z: 19, symbol: 'K', name: 'Kali', nameEn: 'Potassium', mass: 39.10, category: 'alkali-metal', row: 4, col: 1 },
  { z: 20, symbol: 'Ca', name: 'Canxi', nameEn: 'Calcium', mass: 40.08, category: 'alkaline-earth', row: 4, col: 2 },
  { z: 21, symbol: 'Sc', name: 'Scandi', nameEn: 'Scandium', mass: 44.96, category: 'transition-metal', row: 4, col: 3 },
  { z: 22, symbol: 'Ti', name: 'Titan', nameEn: 'Titanium', mass: 47.87, category: 'transition-metal', row: 4, col: 4 },
  { z: 23, symbol: 'V', name: 'Vanadi', nameEn: 'Vanadium', mass: 50.94, category: 'transition-metal', row: 4, col: 5 },
  { z: 24, symbol: 'Cr', name: 'Crom', nameEn: 'Chromium', mass: 52.00, category: 'transition-metal', row: 4, col: 6 },
  { z: 25, symbol: 'Mn', name: 'Mangan', nameEn: 'Manganese', mass: 54.94, category: 'transition-metal', row: 4, col: 7 },
  { z: 26, symbol: 'Fe', name: 'Sắt', nameEn: 'Iron', mass: 55.85, category: 'transition-metal', row: 4, col: 8 },
  { z: 27, symbol: 'Co', name: 'Coban', nameEn: 'Cobalt', mass: 58.93, category: 'transition-metal', row: 4, col: 9 },
  { z: 28, symbol: 'Ni', name: 'Niken', nameEn: 'Nickel', mass: 58.69, category: 'transition-metal', row: 4, col: 10 },
  { z: 29, symbol: 'Cu', name: 'Đồng', nameEn: 'Copper', mass: 63.55, category: 'transition-metal', row: 4, col: 11 },
  { z: 30, symbol: 'Zn', name: 'Kẽm', nameEn: 'Zinc', mass: 65.38, category: 'transition-metal', row: 4, col: 12 },
  { z: 31, symbol: 'Ga', name: 'Gali', nameEn: 'Gallium', mass: 69.72, category: 'post-transition', row: 4, col: 13 },
  { z: 32, symbol: 'Ge', name: 'Gecmani', nameEn: 'Germanium', mass: 72.63, category: 'metalloid', row: 4, col: 14 },
  { z: 33, symbol: 'As', name: 'Asen', nameEn: 'Arsenic', mass: 74.92, category: 'metalloid', row: 4, col: 15 },
  { z: 34, symbol: 'Se', name: 'Selen', nameEn: 'Selenium', mass: 78.97, category: 'nonmetal', row: 4, col: 16 },
  { z: 35, symbol: 'Br', name: 'Brom', nameEn: 'Bromine', mass: 79.90, category: 'halogen', row: 4, col: 17 },
  { z: 36, symbol: 'Kr', name: 'Kripton', nameEn: 'Krypton', mass: 83.80, category: 'noble-gas', row: 4, col: 18 },
  // Period 5
  { z: 37, symbol: 'Rb', name: 'Rubidi', nameEn: 'Rubidium', mass: 85.47, category: 'alkali-metal', row: 5, col: 1 },
  { z: 38, symbol: 'Sr', name: 'Stronti', nameEn: 'Strontium', mass: 87.62, category: 'alkaline-earth', row: 5, col: 2 },
  { z: 39, symbol: 'Y', name: 'Ytri', nameEn: 'Yttrium', mass: 88.91, category: 'transition-metal', row: 5, col: 3 },
  { z: 40, symbol: 'Zr', name: 'Ziriconi', nameEn: 'Zirconium', mass: 91.22, category: 'transition-metal', row: 5, col: 4 },
  { z: 41, symbol: 'Nb', name: 'Niobi', nameEn: 'Niobium', mass: 92.91, category: 'transition-metal', row: 5, col: 5 },
  { z: 42, symbol: 'Mo', name: 'Molipđen', nameEn: 'Molybdenum', mass: 95.95, category: 'transition-metal', row: 5, col: 6 },
  { z: 43, symbol: 'Tc', name: 'Tecneti', nameEn: 'Technetium', mass: 98, category: 'transition-metal', row: 5, col: 7 },
  { z: 44, symbol: 'Ru', name: 'Ruteni', nameEn: 'Ruthenium', mass: 101.1, category: 'transition-metal', row: 5, col: 8 },
  { z: 45, symbol: 'Rh', name: 'Rođi', nameEn: 'Rhodium', mass: 102.9, category: 'transition-metal', row: 5, col: 9 },
  { z: 46, symbol: 'Pd', name: 'Palađi', nameEn: 'Palladium', mass: 106.4, category: 'transition-metal', row: 5, col: 10 },
  { z: 47, symbol: 'Ag', name: 'Bạc', nameEn: 'Silver', mass: 107.9, category: 'transition-metal', row: 5, col: 11 },
  { z: 48, symbol: 'Cd', name: 'Cađimi', nameEn: 'Cadmium', mass: 112.4, category: 'transition-metal', row: 5, col: 12 },
  { z: 49, symbol: 'In', name: 'Inđi', nameEn: 'Indium', mass: 114.8, category: 'post-transition', row: 5, col: 13 },
  { z: 50, symbol: 'Sn', name: 'Thiếc', nameEn: 'Tin', mass: 118.7, category: 'post-transition', row: 5, col: 14 },
  { z: 51, symbol: 'Sb', name: 'Antimon', nameEn: 'Antimony', mass: 121.8, category: 'metalloid', row: 5, col: 15 },
  { z: 52, symbol: 'Te', name: 'Telu', nameEn: 'Tellurium', mass: 127.6, category: 'metalloid', row: 5, col: 16 },
  { z: 53, symbol: 'I', name: 'Iot', nameEn: 'Iodine', mass: 126.9, category: 'halogen', row: 5, col: 17 },
  { z: 54, symbol: 'Xe', name: 'Xenon', nameEn: 'Xenon', mass: 131.3, category: 'noble-gas', row: 5, col: 18 },
  // Period 6
  { z: 55, symbol: 'Cs', name: 'Xesi', nameEn: 'Caesium', mass: 132.9, category: 'alkali-metal', row: 6, col: 1 },
  { z: 56, symbol: 'Ba', name: 'Bari', nameEn: 'Barium', mass: 137.3, category: 'alkaline-earth', row: 6, col: 2 },
  // Lanthanides (row 9 for display)
  { z: 57, symbol: 'La', name: 'Lantan', nameEn: 'Lanthanum', mass: 138.9, category: 'lanthanide', row: 9, col: 3 },
  { z: 58, symbol: 'Ce', name: 'Xeri', nameEn: 'Cerium', mass: 140.1, category: 'lanthanide', row: 9, col: 4 },
  { z: 59, symbol: 'Pr', name: 'Praseođim', nameEn: 'Praseodymium', mass: 140.9, category: 'lanthanide', row: 9, col: 5 },
  { z: 60, symbol: 'Nd', name: 'Neođim', nameEn: 'Neodymium', mass: 144.2, category: 'lanthanide', row: 9, col: 6 },
  { z: 61, symbol: 'Pm', name: 'Prometi', nameEn: 'Promethium', mass: 145, category: 'lanthanide', row: 9, col: 7 },
  { z: 62, symbol: 'Sm', name: 'Samari', nameEn: 'Samarium', mass: 150.4, category: 'lanthanide', row: 9, col: 8 },
  { z: 63, symbol: 'Eu', name: 'Europi', nameEn: 'Europium', mass: 152.0, category: 'lanthanide', row: 9, col: 9 },
  { z: 64, symbol: 'Gd', name: 'Gađolini', nameEn: 'Gadolinium', mass: 157.3, category: 'lanthanide', row: 9, col: 10 },
  { z: 65, symbol: 'Tb', name: 'Tecbi', nameEn: 'Terbium', mass: 158.9, category: 'lanthanide', row: 9, col: 11 },
  { z: 66, symbol: 'Dy', name: 'Đysprosi', nameEn: 'Dysprosium', mass: 162.5, category: 'lanthanide', row: 9, col: 12 },
  { z: 67, symbol: 'Ho', name: 'Honmi', nameEn: 'Holmium', mass: 164.9, category: 'lanthanide', row: 9, col: 13 },
  { z: 68, symbol: 'Er', name: 'Erbi', nameEn: 'Erbium', mass: 167.3, category: 'lanthanide', row: 9, col: 14 },
  { z: 69, symbol: 'Tm', name: 'Tuli', nameEn: 'Thulium', mass: 168.9, category: 'lanthanide', row: 9, col: 15 },
  { z: 70, symbol: 'Yb', name: 'Ytecbi', nameEn: 'Ytterbium', mass: 173.0, category: 'lanthanide', row: 9, col: 16 },
  { z: 71, symbol: 'Lu', name: 'Luteti', nameEn: 'Lutetium', mass: 175.0, category: 'lanthanide', row: 9, col: 17 },
  // Continue Period 6
  { z: 72, symbol: 'Hf', name: 'Hafni', nameEn: 'Hafnium', mass: 178.5, category: 'transition-metal', row: 6, col: 4 },
  { z: 73, symbol: 'Ta', name: 'Tantan', nameEn: 'Tantalum', mass: 180.9, category: 'transition-metal', row: 6, col: 5 },
  { z: 74, symbol: 'W', name: 'Vonfram', nameEn: 'Tungsten', mass: 183.8, category: 'transition-metal', row: 6, col: 6 },
  { z: 75, symbol: 'Re', name: 'Reni', nameEn: 'Rhenium', mass: 186.2, category: 'transition-metal', row: 6, col: 7 },
  { z: 76, symbol: 'Os', name: 'Osimi', nameEn: 'Osmium', mass: 190.2, category: 'transition-metal', row: 6, col: 8 },
  { z: 77, symbol: 'Ir', name: 'Iriđi', nameEn: 'Iridium', mass: 192.2, category: 'transition-metal', row: 6, col: 9 },
  { z: 78, symbol: 'Pt', name: 'Platin', nameEn: 'Platinum', mass: 195.1, category: 'transition-metal', row: 6, col: 10 },
  { z: 79, symbol: 'Au', name: 'Vàng', nameEn: 'Gold', mass: 197.0, category: 'transition-metal', row: 6, col: 11 },
  { z: 80, symbol: 'Hg', name: 'Thuỷ ngân', nameEn: 'Mercury', mass: 200.6, category: 'transition-metal', row: 6, col: 12 },
  { z: 81, symbol: 'Tl', name: 'Tali', nameEn: 'Thallium', mass: 204.4, category: 'post-transition', row: 6, col: 13 },
  { z: 82, symbol: 'Pb', name: 'Chì', nameEn: 'Lead', mass: 207.2, category: 'post-transition', row: 6, col: 14 },
  { z: 83, symbol: 'Bi', name: 'Bitmut', nameEn: 'Bismuth', mass: 209.0, category: 'post-transition', row: 6, col: 15 },
  { z: 84, symbol: 'Po', name: 'Poloni', nameEn: 'Polonium', mass: 209, category: 'post-transition', row: 6, col: 16 },
  { z: 85, symbol: 'At', name: 'Atatin', nameEn: 'Astatine', mass: 210, category: 'halogen', row: 6, col: 17 },
  { z: 86, symbol: 'Rn', name: 'Rađon', nameEn: 'Radon', mass: 222, category: 'noble-gas', row: 6, col: 18 },
  // Period 7
  { z: 87, symbol: 'Fr', name: 'Franxi', nameEn: 'Francium', mass: 223, category: 'alkali-metal', row: 7, col: 1 },
  { z: 88, symbol: 'Ra', name: 'Rađi', nameEn: 'Radium', mass: 226, category: 'alkaline-earth', row: 7, col: 2 },
  // Actinides (row 10 for display)
  { z: 89, symbol: 'Ac', name: 'Actini', nameEn: 'Actinium', mass: 227, category: 'actinide', row: 10, col: 3 },
  { z: 90, symbol: 'Th', name: 'Thori', nameEn: 'Thorium', mass: 232.0, category: 'actinide', row: 10, col: 4 },
  { z: 91, symbol: 'Pa', name: 'Protactini', nameEn: 'Protactinium', mass: 231.0, category: 'actinide', row: 10, col: 5 },
  { z: 92, symbol: 'U', name: 'Urani', nameEn: 'Uranium', mass: 238.0, category: 'actinide', row: 10, col: 6 },
  { z: 93, symbol: 'Np', name: 'Neptuni', nameEn: 'Neptunium', mass: 237, category: 'actinide', row: 10, col: 7 },
  { z: 94, symbol: 'Pu', name: 'Plutoni', nameEn: 'Plutonium', mass: 244, category: 'actinide', row: 10, col: 8 },
  { z: 95, symbol: 'Am', name: 'Americi', nameEn: 'Americium', mass: 243, category: 'actinide', row: 10, col: 9 },
  { z: 96, symbol: 'Cm', name: 'Curi', nameEn: 'Curium', mass: 247, category: 'actinide', row: 10, col: 10 },
  { z: 97, symbol: 'Bk', name: 'Beckeli', nameEn: 'Berkelium', mass: 247, category: 'actinide', row: 10, col: 11 },
  { z: 98, symbol: 'Cf', name: 'Californi', nameEn: 'Californium', mass: 251, category: 'actinide', row: 10, col: 12 },
  { z: 99, symbol: 'Es', name: 'Ensteni', nameEn: 'Einsteinium', mass: 252, category: 'actinide', row: 10, col: 13 },
  { z: 100, symbol: 'Fm', name: 'Fecmi', nameEn: 'Fermium', mass: 257, category: 'actinide', row: 10, col: 14 },
  { z: 101, symbol: 'Md', name: 'Menđelevi', nameEn: 'Mendelevium', mass: 258, category: 'actinide', row: 10, col: 15 },
  { z: 102, symbol: 'No', name: 'Nobeli', nameEn: 'Nobelium', mass: 259, category: 'actinide', row: 10, col: 16 },
  { z: 103, symbol: 'Lr', name: 'Lawrenci', nameEn: 'Lawrencium', mass: 266, category: 'actinide', row: 10, col: 17 },
  // Continue Period 7
  { z: 104, symbol: 'Rf', name: 'Rutherforđi', nameEn: 'Rutherfordium', mass: 267, category: 'transition-metal', row: 7, col: 4 },
  { z: 105, symbol: 'Db', name: 'Dubni', nameEn: 'Dubnium', mass: 270, category: 'transition-metal', row: 7, col: 5 },
  { z: 106, symbol: 'Sg', name: 'Siaborgi', nameEn: 'Seaborgium', mass: 271, category: 'transition-metal', row: 7, col: 6 },
  { z: 107, symbol: 'Bh', name: 'Bohri', nameEn: 'Bohrium', mass: 270, category: 'transition-metal', row: 7, col: 7 },
  { z: 108, symbol: 'Hs', name: 'Hassi', nameEn: 'Hassium', mass: 277, category: 'transition-metal', row: 7, col: 8 },
  { z: 109, symbol: 'Mt', name: 'Meitneri', nameEn: 'Meitnerium', mass: 278, category: 'transition-metal', row: 7, col: 9 },
  { z: 110, symbol: 'Ds', name: 'Darmstadti', nameEn: 'Darmstadtium', mass: 281, category: 'transition-metal', row: 7, col: 10 },
  { z: 111, symbol: 'Rg', name: 'Roentgeni', nameEn: 'Roentgenium', mass: 282, category: 'transition-metal', row: 7, col: 11 },
  { z: 112, symbol: 'Cn', name: 'Copernici', nameEn: 'Copernicium', mass: 285, category: 'transition-metal', row: 7, col: 12 },
  { z: 113, symbol: 'Nh', name: 'Nihoni', nameEn: 'Nihonium', mass: 286, category: 'post-transition', row: 7, col: 13 },
  { z: 114, symbol: 'Fl', name: 'Flerovi', nameEn: 'Flerovium', mass: 289, category: 'post-transition', row: 7, col: 14 },
  { z: 115, symbol: 'Mc', name: 'Moscovi', nameEn: 'Moscovium', mass: 290, category: 'post-transition', row: 7, col: 15 },
  { z: 116, symbol: 'Lv', name: 'Livermori', nameEn: 'Livermorium', mass: 293, category: 'post-transition', row: 7, col: 16 },
  { z: 117, symbol: 'Ts', name: 'Tennessine', nameEn: 'Tennessine', mass: 294, category: 'halogen', row: 7, col: 17 },
  { z: 118, symbol: 'Og', name: 'Oganesson', nameEn: 'Oganesson', mass: 294, category: 'noble-gas', row: 7, col: 18 },
];

// Lanthanide/Actinide placeholder markers for the main table
export const LANTHANIDE_MARKER = { symbol: 'La-Lu', name: '57-71', category: 'lanthanide', row: 6, col: 3, isMarker: true };
export const ACTINIDE_MARKER = { symbol: 'Ac-Lr', name: '89-103', category: 'actinide', row: 7, col: 3, isMarker: true };

export const CATEGORY_COLORS = {
  'alkali-metal': { bg: 'bg-red-100', border: 'border-red-300', text: 'text-red-800', label: 'Kim loại kiềm' },
  'alkaline-earth': { bg: 'bg-orange-100', border: 'border-orange-300', text: 'text-orange-800', label: 'Kim loại kiềm thổ' },
  'transition-metal': { bg: 'bg-yellow-100', border: 'border-yellow-300', text: 'text-yellow-800', label: 'Kim loại chuyển tiếp' },
  'post-transition': { bg: 'bg-green-100', border: 'border-green-300', text: 'text-green-800', label: 'Kim loại sau chuyển tiếp' },
  'metalloid': { bg: 'bg-teal-100', border: 'border-teal-300', text: 'text-teal-800', label: 'Á kim' },
  'nonmetal': { bg: 'bg-sky-100', border: 'border-sky-300', text: 'text-sky-800', label: 'Phi kim' },
  'halogen': { bg: 'bg-cyan-100', border: 'border-cyan-300', text: 'text-cyan-800', label: 'Halogen' },
  'noble-gas': { bg: 'bg-purple-100', border: 'border-purple-300', text: 'text-purple-800', label: 'Khí hiếm' },
  'lanthanide': { bg: 'bg-pink-100', border: 'border-pink-300', text: 'text-pink-800', label: 'Lanthanide' },
  'actinide': { bg: 'bg-rose-100', border: 'border-rose-300', text: 'text-rose-800', label: 'Actinide' },
};

export const REACTIONS_DATA = [
  {
    reactantA: 'HCl', reactantAName: 'Dung dịch HCl (Axit clohidric)',
    reactantB: 'CaCO3', reactantBName: 'CaCO₃ (Canxi cacbonat)',
    equation: '2HCl + CaCO₃ → CaCl₂ + H₂O + CO₂↑',
    phenomenon: 'Viên đá vôi tan dần, sủi bọt khí không màu (CO₂). Dung dịch trong suốt.',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#e8f5e9', colorB: '#e0e0e0', resultColor: '#f5f5f5',
      solidB: true, solidBColor: '#bdbdbd', solidBLabel: 'CaCO₃',
      effects: ['bubbles'], bubbleColor: 'rgba(200,200,200,0.6)',
      emoji: '🧱', gasLabel: 'CO₂↑',
    },
  },
  {
    reactantA: 'NaOH', reactantAName: 'Dung dịch NaOH (Natri hidroxit)',
    reactantB: 'HCl', reactantBName: 'Dung dịch HCl (Axit clohidric)',
    equation: 'NaOH + HCl → NaCl + H₂O',
    phenomenon: 'Phản ứng trung hòa. Không có hiện tượng quan sát rõ ràng bằng mắt. Dung dịch nóng lên nhẹ.',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#bbdefb', colorB: '#c8e6c9', resultColor: '#e3f2fd',
      effects: ['heat'], emoji: '🌡️',
    },
  },
  {
    reactantA: 'H2SO4', reactantAName: 'Dung dịch H₂SO₄ loãng (Axit sunfuric)',
    reactantB: 'Fe', reactantBName: 'Fe (Sắt)',
    equation: 'Fe + H₂SO₄ → FeSO₄ + H₂↑',
    phenomenon: 'Sắt tan dần, sủi bọt khí không màu (H₂). Dung dịch chuyển sang màu xanh nhạt (FeSO₄).',
    conditions: 'Nhiệt độ thường, H₂SO₄ loãng',
    visual: {
      colorA: '#fff9c4', colorB: '#e0e0e0', resultColor: '#e0f2f1',
      solidB: true, solidBColor: '#78909c', solidBLabel: 'Fe',
      effects: ['bubbles', 'colorChange'], bubbleColor: 'rgba(200,200,200,0.5)',
      emoji: '⚙️', gasLabel: 'H₂↑',
    },
  },
  {
    reactantA: 'NaOH', reactantAName: 'Dung dịch NaOH (Natri hidroxit)',
    reactantB: 'CuSO4', reactantBName: 'Dung dịch CuSO₄ (Đồng sunfat)',
    equation: '2NaOH + CuSO₄ → Cu(OH)₂↓ + Na₂SO₄',
    phenomenon: 'Xuất hiện kết tủa màu xanh lam Cu(OH)₂ lơ lửng trong dung dịch.',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#bbdefb', colorB: '#64b5f6', resultColor: '#90caf9',
      effects: ['precipitate'], precipitateColor: '#1e88e5',
      emoji: '💎', precipitateLabel: 'Cu(OH)₂↓',
    },
  },
  {
    reactantA: 'AgNO3', reactantAName: 'Dung dịch AgNO₃ (Bạc nitrat)',
    reactantB: 'NaCl', reactantBName: 'Dung dịch NaCl (Natri clorua)',
    equation: 'AgNO₃ + NaCl → AgCl↓ + NaNO₃',
    phenomenon: 'Xuất hiện kết tủa trắng AgCl lắng xuống đáy. Kết tủa không tan trong axit loãng.',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#f5f5f5', colorB: '#f5f5f5', resultColor: '#fafafa',
      effects: ['precipitate'], precipitateColor: '#e0e0e0',
      emoji: '🪨', precipitateLabel: 'AgCl↓',
    },
  },
  {
    reactantA: 'Na', reactantAName: 'Na (Natri kim loại)',
    reactantB: 'H2O', reactantBName: 'H₂O (Nước)',
    equation: '2Na + 2H₂O → 2NaOH + H₂↑',
    phenomenon: 'Na chạy trên mặt nước, tan dần thành giọt tròn sáng bóng. Sủi bọt mạnh (H₂). Tỏa nhiệt mạnh.',
    conditions: 'Nhiệt độ thường, phản ứng tự xảy ra mãnh liệt',
    visual: {
      colorA: '#e0e0e0', colorB: '#e3f2fd', resultColor: '#bbdefb',
      solidA: true, solidAColor: '#9e9e9e', solidALabel: 'Na',
      effects: ['bubbles', 'fire', 'heat'], bubbleColor: 'rgba(255,255,255,0.7)',
      emoji: '🔥', gasLabel: 'H₂↑', intense: true,
    },
  },
  {
    reactantA: 'BaCl2', reactantAName: 'Dung dịch BaCl₂ (Bari clorua)',
    reactantB: 'H2SO4', reactantBName: 'Dung dịch H₂SO₄ (Axit sunfuric)',
    equation: 'BaCl₂ + H₂SO₄ → BaSO₄↓ + 2HCl',
    phenomenon: 'Xuất hiện kết tủa trắng BaSO₄, không tan trong axit. Nhận biết gốc sunfat.',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#f5f5f5', colorB: '#fff9c4', resultColor: '#f5f5f5',
      effects: ['precipitate'], precipitateColor: '#eeeeee',
      emoji: '⬜', precipitateLabel: 'BaSO₄↓',
    },
  },
  {
    reactantA: 'Zn', reactantAName: 'Zn (Kẽm)',
    reactantB: 'HCl', reactantBName: 'Dung dịch HCl (Axit clohidric)',
    equation: 'Zn + 2HCl → ZnCl₂ + H₂↑',
    phenomenon: 'Kẽm tan dần, sủi bọt khí mạnh (H₂). Dung dịch trong suốt.',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#e0e0e0', colorB: '#e8f5e9', resultColor: '#f5f5f5',
      solidA: true, solidAColor: '#90a4ae', solidALabel: 'Zn',
      effects: ['bubbles'], bubbleColor: 'rgba(200,200,200,0.5)',
      emoji: '⚗️', gasLabel: 'H₂↑',
    },
  },
  {
    reactantA: 'Mg', reactantAName: 'Mg (Magie)',
    reactantB: 'HCl', reactantBName: 'Dung dịch HCl (Axit clohidric)',
    equation: 'Mg + 2HCl → MgCl₂ + H₂↑',
    phenomenon: 'Magie tan nhanh, sủi bọt khí mạnh (H₂). Dung dịch trong suốt, tỏa nhiệt.',
    conditions: 'Nhiệt độ thường, phản ứng nhanh',
    visual: {
      colorA: '#e0e0e0', colorB: '#e8f5e9', resultColor: '#f5f5f5',
      solidA: true, solidAColor: '#bdbdbd', solidALabel: 'Mg',
      effects: ['bubbles', 'heat'], bubbleColor: 'rgba(200,200,200,0.6)',
      emoji: '💨', gasLabel: 'H₂↑',
    },
  },
  {
    reactantA: 'CuSO4', reactantAName: 'Dung dịch CuSO₄ (Đồng sunfat)',
    reactantB: 'Fe', reactantBName: 'Fe (Đinh sắt)',
    equation: 'CuSO₄ + Fe → FeSO₄ + Cu↓',
    phenomenon: 'Đinh sắt dần bị phủ lớp đồng đỏ. Dung dịch chuyển từ xanh sang xanh nhạt (FeSO₄).',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#64b5f6', colorB: '#e0e0e0', resultColor: '#e0f2f1',
      solidB: true, solidBColor: '#78909c', solidBLabel: 'Fe',
      effects: ['colorChange', 'precipitate'], precipitateColor: '#e65100',
      emoji: '🪙', precipitateLabel: 'Cu↓',
    },
  },
  {
    reactantA: 'NaOH', reactantAName: 'Dung dịch NaOH (Natri hidroxit)',
    reactantB: 'FeCl3', reactantBName: 'Dung dịch FeCl₃ (Sắt(III) clorua)',
    equation: '3NaOH + FeCl₃ → Fe(OH)₃↓ + 3NaCl',
    phenomenon: 'Xuất hiện kết tủa nâu đỏ Fe(OH)₃ lơ lửng.',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#bbdefb', colorB: '#ffcc80', resultColor: '#ffe0b2',
      effects: ['precipitate'], precipitateColor: '#bf360c',
      emoji: '🟤', precipitateLabel: 'Fe(OH)₃↓',
    },
  },
  {
    reactantA: 'Na2CO3', reactantAName: 'Dung dịch Na₂CO₃ (Natri cacbonat)',
    reactantB: 'HCl', reactantBName: 'Dung dịch HCl (Axit clohidric)',
    equation: 'Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑',
    phenomenon: 'Sủi bọt khí không màu (CO₂). Dung dịch trong suốt.',
    conditions: 'Nhiệt độ thường',
    visual: {
      colorA: '#f5f5f5', colorB: '#e8f5e9', resultColor: '#f5f5f5',
      effects: ['bubbles'], bubbleColor: 'rgba(200,200,200,0.6)',
      emoji: '🫧', gasLabel: 'CO₂↑',
    },
  },
];
